import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      spacing: {
        "card-gap": "24px",
        "bento-padding": "32px",
        "unit": "8px",
        "container-padding": "24px",
      },
      colors: {
        "on-primary-fixed": "#1c0062",
        "inverse-primary": "#cabeff",
        "on-tertiary-fixed-variant": "#574400",
        "foreground": "#2c3152",
        "tertiary-fixed-dim": "#e9c34d",
        "on-error": "#ffffff",
        "tertiary-container": "#cba734",
        "on-primary-fixed-variant": "#493598",
        "on-error-container": "#93000a",
        "tertiary": "#745b00",
        "surface-bright": "#fdf8ff",
        "on-tertiary-container": "#4e3d00",
        "inverse-on-surface": "#f4eff8",
        "error-container": "#ffdad6",
        "surface-container": "#f1ecf5",
        "surface": "#fdf8ff",
        "card": "#ffffff",
        "primary-fixed-dim": "#cabeff",
        "on-primary-container": "#fffbff",
        "destructive": "#e54d68",
        "inverse-surface": "#312f36",
        "surface-tint": "#614fb1",
        "on-tertiary": "#ffffff",
        "emotion-surprised": "#ce9edc",
        "surface-container-lowest": "#ffffff",
        "background": "#f4f6f9",
        "on-secondary": "#ffffff",
        "accent": "#8fcbe9",
        "text-primary": "#1e293b",
        "on-tertiary-fixed": "#241a00",
        "secondary": "#006c53",
        "surface-container-low": "#f7f2fb",
        "on-primary": "#ffffff",
        "surface-variant": "#e6e1ea",
        "secondary-container": "#9cf4d3",
        "primary-fixed": "#e6deff",
        "emotion-scared": "#b48fd3",
        "secondary-fixed-dim": "#80d7b8",
        "on-background": "#1c1b21",
        "secondary-fixed": "#9cf4d3",
        "surface-container-highest": "#e6e1ea",
        "outline": "#797583",
        "on-secondary-fixed-variant": "#00513e",
        "outline-variant": "#c9c4d4",
        "emotion-excited": "#ebbb7a",
        "error": "#ba1a1a",
        "text-secondary": "#64748b",
        "tertiary-fixed": "#ffe08a",
        "on-secondary-container": "#087258",
        "app-bg-gradient": "radial-gradient(ellipse 80% 60% at 10% 10%, hsla(250 50% 85% / 0.12), transparent 60%), radial-gradient(ellipse 70% 50% at 90% 20%, hsla(200 50% 82% / 0.10), transparent 55%), radial-gradient(ellipse 60% 45% at 60% 90%, hsla(160 40% 80% / 0.10), transparent 55%), linear-gradient(180deg, hsl(210 30% 97%), hsl(220 25% 96%))",
        "on-surface-variant": "#484552",
        "surface-container-high": "#ebe6ef",
        "surface-dim": "#ddd8e1",
        "emotion-sad": "#90a7da",
        "primary-container": "#7765c9",
        "on-surface": "#1c1b21",
        "emotion-angry": "#e57f7f",
        "primary": "#5e4caf",
        "emotion-happy": "#f2df79",
        "success": "#5eb98f",
        "on-secondary-fixed": "#002117",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#5e4caf",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "#006c53",
          foreground: "#ffffff",
        },
        destructive: {
          DEFAULT: "#ba1a1a",
          foreground: "#ffffff",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "#8fcbe9",
          foreground: "hsl(var(--accent-foreground))",
        },
        success: {
          DEFAULT: "#5eb98f",
          foreground: "#ffffff",
        },
        popover: {
          DEFAULT: "#fdf8ff",
          foreground: "#1c1b21",
        },
        card: {
          DEFAULT: "#ffffff",
          foreground: "#1c1b21",
        },
        emotion: {
          happy: "#f2df79",
          sad: "#90a7da",
          angry: "#e57f7f",
          surprised: "#ce9edc",
          scared: "#b48fd3",
          excited: "#ebbb7a",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "#5e4caf",
          "primary-foreground": "#ffffff",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "#5e4caf",
        },

      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        heading: ["Quicksand", "sans-serif"],
        body: ["Nunito", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "bounce-gentle": "bounce-gentle 2s ease-in-out infinite",
        "float": "float 3s ease-in-out infinite",
        "scale-in": "scale-in 0.3s ease-out",
        "slide-up": "slide-up 0.5s ease-out",
        "fade-in": "fade-in 0.4s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
