import { PrismaClient, QuestionType, AnswerChoice } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  const hashedPassword = await bcrypt.hash('123456', 10);

  await prisma.user.create({
    data: {
      id: '1',
      name: 'admin',
      email: 'admin@gmail.com',
      password: hashedPassword,
    },
  });

  await prisma.emotion.createMany({
    data: [
      {
        id: '1',
        name: 'Vui vẻ',
        iconUrl: 'media_emotion/happy.png',
      },
      {
        id: '2',
        name: 'Buồn bã',
        iconUrl: 'media_emotion/sad.png',
      },
      {
        id: '3',
        name: 'Giận dữ',
        iconUrl: 'media_emotion/angry.png',
      },
      {
        id: '4',
        name: 'Ngạc nhiên',
        iconUrl: 'media_emotion/surprised.png',
      },
      {
        id: '5',
        name: 'Sợ hãi',
        iconUrl: 'media_emotion/fear.png',
      },
      {
        id: '6',
        name: 'Ghê tởm',
        iconUrl: 'media_emotion/disgusted.png',
      },
      {
        id: '7',
        name: 'Bình tĩnh',
        iconUrl: 'media_emotion/neutral.png',
      },
    ],
  });

  await prisma.level.createMany({
    data: [
      {
        id: '1',
        name: 'Cảm xúc cơ bản',
        difficulty: 1,
        requiredPoints: 0,
      },
      {
        id: '2',
        name: 'Cảm xúc phổ biến',
        difficulty: 2,
        requiredPoints: 18,
      },
      {
        id: '3',
        name: 'Cảm xúc xã hội',
        difficulty: 3,
        requiredPoints: 36,
      },
      {
        id: '4',
        name: 'Nhiều lựa chon đúng',
        difficulty: 4,
        requiredPoints: 64,
      },
    ],
  });

  // Level 1 (difficulty=1) is automatically unlocked because user.currentLevel defaults to 1
  // Other levels unlock progressively as the user earns enough points

  await prisma.quiz.createMany({
    data: [
      {
        id: '1',
        levelId: '1',
        title: 'Nhận diện Gương mặt',
      },
      {
        id: '2',
        levelId: '1',
        title: 'Cảm xúc trong Tình huống',
      },
      {
        id: '3',
        levelId: '2',
        title: 'Những Gương mặt Mới',
      },
      {
        id: '4',
        levelId: '2',
        title: 'Cảm xúc trong Tình huống phổ biến',
      },
      {
        id: '5',
        levelId: '3',
        title: 'Khi ở cùng Người khác',
      },
      {
        id: '6',
        levelId: '3',
        title: 'Cảm xúc của đối phương',
      },
      {
        id: '7',
        levelId: '4',
        title: 'Cảm xúc bên trong',
      },
    ],
  });

  await prisma.question.createMany({
    // level1 quiz1
    data: [
      {
        quizId: '1',
        emotionId: '1',
        questionType: QuestionType.image,
        content: 'Icon này thể hiện cảm xúc gì?',
        mediaUrl: 'media_question/level1/quiz1/q1.jpg',
        optionA: 'Buồn bã',
        optionB: 'Vui vẻ',
        optionC: 'Sợ hãi',
        optionD: 'Bình tĩnh',
        correctAnswer: AnswerChoice.B,
      },
      {
        quizId: '1',
        emotionId: '2',
        questionType: QuestionType.image,
        content: 'Người trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level1/quiz1/q2.jpg',
        optionA: 'Buồn bã',
        optionB: 'Bình tĩnh',
        optionC: 'Ngạc nhiên',
        optionD: 'Sợ hãi',
        correctAnswer: AnswerChoice.A,
      },
      {
        quizId: '1',
        emotionId: '1',
        questionType: QuestionType.video,
        content: 'Người trong video thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level1/quiz1/q3.mp4',
        optionA: 'Bình tĩnh',
        optionB: 'Sợ hãi',
        optionC: 'Vui vẻ',
        optionD: 'Giận dữ',
        correctAnswer: AnswerChoice.C,
      },
      {
        quizId: '1',
        emotionId: '4',
        questionType: QuestionType.image,
        content: 'Icon trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level1/quiz1/q4.jpg',
        optionA: 'Sợ hãi',
        optionB: 'Buồn bã',
        optionC: 'Giận dữ',
        optionD: 'Ngạc nhiên',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '1',
        emotionId: '3',
        questionType: QuestionType.image,
        content: 'Người trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level1/quiz1/q5.jpg',
        optionA: 'Ghê tởm',
        optionB: 'Giận dữ',
        optionC: 'Vui vẻ',
        optionD: 'Bình tĩnh',
        correctAnswer: AnswerChoice.B,
      },
      {
        quizId: '1',
        emotionId: '7',
        questionType: QuestionType.image,
        content: 'Người trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level1/quiz1/q6.jpg',
        optionA: 'Bình tĩnh',
        optionB: 'Sợ hãi',
        optionC: 'Buồn bã',
        optionD: 'Vui vẻ',
        correctAnswer: AnswerChoice.A,
      },
      {
        quizId: '1',
        emotionId: '1',
        questionType: QuestionType.image,
        content: 'Người trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level1/quiz1/q7.jpg',
        optionA: 'Sợ hãi',
        optionB: 'Buồn bã',
        optionC: 'Vui vẻ',
        optionD: 'Giận dữ',
        correctAnswer: AnswerChoice.C,
      },
      {
        quizId: '1',
        emotionId: '6',
        questionType: QuestionType.image,
        content: 'Icon trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level1/quiz1/q8.jpg',
        optionA: 'Buồn bã',
        optionB: 'Ghê tởm',
        optionC: 'Ngạc nhiên',
        optionD: 'Giận dữ',
        correctAnswer: AnswerChoice.B,
      },

      // level1 quiz2
      {
        quizId: '2',
        emotionId: '1',
        questionType: QuestionType.text,
        content: 'Khi bạn được mẹ tặng quà sinh nhật, bạn cảm thấy...',
        optionA: 'Vui vẻ',
        optionB: 'Giận dữ',
        optionC: 'Sợ hãi',
        optionD: 'Bình tĩnh',
        correctAnswer: AnswerChoice.A,
      },
      {
        quizId: '2',
        emotionId: '2',
        questionType: QuestionType.text,
        content: 'Khi bạn bị mất món đồ chơi yêu thích, bạn cảm thấy...',
        optionA: 'Vui vẻ',
        optionB: 'Buồn bã',
        optionC: 'Giận dữ',
        optionD: 'Sợ hãi',
        correctAnswer: AnswerChoice.B,
      },
      {
        quizId: '2',
        emotionId: '3',
        questionType: QuestionType.text,
        content: 'Khi có bạn khác giật đồ chơi của bạn, bạn cảm thấy...',
        optionA: 'Ghê tởm',
        optionB: 'Ngạc nhiên',
        optionC: 'Bình tĩnh',
        optionD: 'Giận dữ',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '2',
        emotionId: '5',
        questionType: QuestionType.text,
        content:
          'Khi bạn nghe thấy một tiếng động rất lớn trong bóng tối, bạn cảm thấy...',
        optionA: 'Giận dữ',
        optionB: 'Sợ hãi',
        optionC: 'Buồn bã',
        optionD: 'Ngạc nhiên',
        correctAnswer: AnswerChoice.B,
      },
      {
        quizId: '2',
        emotionId: '2',
        questionType: QuestionType.text,
        content: 'An bị ngã xe đạp và bị đau. An cảm thấy...',
        optionA: 'Vui vẻ',
        optionB: 'Ngạc nhiên',
        optionC: 'Buồn bã',
        optionD: 'Bình tĩnh',
        correctAnswer: AnswerChoice.C,
      },
      {
        quizId: '2',
        emotionId: '1',
        questionType: QuestionType.text,
        content: 'Bố mẹ cho bạn đi công viên nước. Bạn cảm thấy...',
        optionA: 'Vui vẻ',
        optionB: 'Giận dữ',
        optionC: 'Buồn bã',
        optionD: 'Sợ hãi',
        correctAnswer: AnswerChoice.A,
      },
      {
        quizId: '2',
        emotionId: '3',
        questionType: QuestionType.text,
        content: 'Bạn bị em bé cắn. Bạn cảm thấy...',
        optionA: 'Ghê tởm',
        optionB: 'Bình tĩnh',
        optionC: 'Vui vẻ',
        optionD: 'Giận dữ',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '2',
        emotionId: '1',
        questionType: QuestionType.text,
        content: 'Bạn mơ thấy một con quái vật. Bạn cảm thấy...',
        optionA: 'Ngạc nhiên',
        optionB: 'Giận dữ',
        optionC: 'Sợ hãi',
        optionD: 'Buồn bã',
        correctAnswer: AnswerChoice.C,
      },

      // level2 quiz1
      {
        quizId: '3',
        emotionId: '2',
        questionType: QuestionType.image,
        content: 'Người trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level2/quiz1/q1.jpg',
        optionA: 'Vui vẻ',
        optionB: 'Buồn bã',
        optionC: 'Ngạc nhiên',
        optionD: 'Giận dữ',
        correctAnswer: AnswerChoice.B,
      },
      {
        quizId: '3',
        emotionId: '4',
        questionType: QuestionType.image,
        content: 'Người trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level2/quiz1/q2.jpg',
        optionA: 'Giận dữ',
        optionB: 'Vui vẻ',
        optionC: 'Buồn bã',
        optionD: 'Ngạc nhiên',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '3',
        emotionId: '3',
        questionType: QuestionType.image,
        content: 'Người trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level2/quiz1/q3.jpg',
        optionA: 'Giận dữ',
        optionB: 'Ghê tởm',
        optionC: 'Buồn bã',
        optionD: 'Vui vẻ',
        correctAnswer: AnswerChoice.A,
      },
      {
        quizId: '3',
        emotionId: '6',
        questionType: QuestionType.image,
        content: 'Người trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level2/quiz1/q4.jpg',
        optionA: 'Ghê tởm',
        optionB: 'Sợ hãi',
        optionC: 'Bình tĩnh',
        optionD: 'Giận dữ',
        correctAnswer: AnswerChoice.A,
      },
      {
        quizId: '3',
        emotionId: '7',
        questionType: QuestionType.image,
        content: 'Người trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level2/quiz1/q5.jpg',
        optionA: 'Vui vẻ',
        optionB: 'Bình tĩnh',
        optionC: 'Giận dữ',
        optionD: 'Buồn bã',
        correctAnswer: AnswerChoice.B,
      },
      {
        quizId: '3',
        emotionId: '5',
        questionType: QuestionType.image,
        content: 'Người trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level2/quiz1/q6.jpg',
        optionA: 'Ghê tởm',
        optionB: 'Vui vẻ',
        optionC: 'Ngạc nhiên',
        optionD: 'Sợ hãi',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '3',
        emotionId: '7',
        questionType: QuestionType.image,
        content: 'Icon trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level2/quiz1/q7.jpg',
        optionA: 'Giận dữ',
        optionB: 'Ghê tởm',
        optionC: 'Bình tĩnh',
        optionD: 'Ngạc nhiên',
        correctAnswer: AnswerChoice.C,
      },
      {
        quizId: '3',
        emotionId: '1',
        questionType: QuestionType.image,
        content: 'Người trong ảnh thể hiện biểu cảm gì?',
        mediaUrl: 'media_question/level2/quiz1/q8.jpg',
        optionA: 'Giận dữ',
        optionB: 'Bình tĩnh',
        optionC: 'Vui vẻ',
        optionD: 'Sợ hãi',
        correctAnswer: AnswerChoice.C,
      },

      // level2 quiz2
      {
        quizId: '4',
        emotionId: '4',
        questionType: QuestionType.text,
        content: 'Bà bất ngờ đến thăm bạn lúc bạn đi học về, bạn cảm thấy...',
        optionA: 'Sợ hãi',
        optionB: 'Bình tĩnh',
        optionC: 'Ngạc nhiên',
        optionD: 'Giận dữ',
        correctAnswer: AnswerChoice.C,
      },
      {
        quizId: '4',
        emotionId: '6',
        questionType: QuestionType.text,
        content: 'Khi bạn đang ăn một món bạn không thích, bạn cảm thấy...',
        optionA: 'Vui vẻ',
        optionB: 'Ghê tởm',
        optionC: 'Giận dữ',
        optionD: 'Ngạc nhiên',
        correctAnswer: AnswerChoice.C,
      },
      {
        quizId: '4',
        emotionId: '2',
        questionType: QuestionType.text,
        content: 'Bạn không được ăn kẹo. Bạn có thể cảm thấy...',
        optionA: 'Buồn bã',
        optionB: 'Bình tĩnh',
        optionC: 'Vui vẻ',
        optionD: 'Ghê tởm',
        correctAnswer: AnswerChoice.A,
      },
      {
        quizId: '4',
        emotionId: '1',
        questionType: QuestionType.text,
        content: 'Bạn được điểm 10. Bạn cảm thấy...',
        optionA: 'Buồn bã',
        optionB: 'Giận dữ',
        optionC: 'Vui vẻ',
        optionD: 'Sợ hãi',
        correctAnswer: AnswerChoice.C,
      },
      {
        quizId: '4',
        emotionId: '4',
        questionType: QuestionType.text,
        content: 'Khi có một bữa tiệc sinh nhật bất ngờ, bạn thấy...',
        optionA: 'Vui vẻ',
        optionB: 'Bình tĩnh',
        optionC: 'Giận dữ',
        optionD: 'Ngạc nhiên',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '4',
        emotionId: '2',
        questionType: QuestionType.text,
        content: 'Khi phải ngồi chờ mẹ mua đồ rất lâu, bạn thấy...',
        optionA: 'Ghê tởm',
        optionB: 'Buồn bã',
        optionC: 'Ngạc nhiên',
        optionD: 'Bình tĩnh',
        correctAnswer: AnswerChoice.B,
      },
      {
        quizId: '4',
        emotionId: '1',
        questionType: QuestionType.text,
        content: 'Khi được cô giáo khen trước cả lớp, bạn có thể cảm thấy...',
        optionA: 'Vui vẻ',
        optionB: 'Bình tĩnh',
        optionC: 'Giận dữ',
        optionD: 'Ghê tởm',
        correctAnswer: AnswerChoice.A,
      },
      {
        quizId: '4',
        emotionId: '1',
        questionType: QuestionType.text,
        content:
          'Sáng mai cả nhà đi dã ngoại, tối nay bạn không ngủ được vì...',
        optionA: 'Ngạc nhiên',
        optionB: 'Bình tĩnh',
        optionC: 'Giận dữ',
        optionD: 'Vui vẻ',
        correctAnswer: AnswerChoice.D,
      },

      // level 3 quiz 1
      {
        quizId: '5',
        emotionId: '2',
        questionType: QuestionType.text,
        content:
          'Bạn thân của con bị ngã và đang khóc. Con cảm thấy buồn theo bạn và muốn giúp đỡ. Cảm xúc đó gọi là gì?',
        optionA: 'Ngạc nhiên',
        optionB: 'Buồn bã',
        optionC: 'Giận dữ',
        optionD: 'Sợ hãi',
        correctAnswer: AnswerChoice.B,
      },
      {
        quizId: '5',
        emotionId: '1',
        questionType: QuestionType.text,
        content:
          'Khi bạn bè cùng nhau làm được một bức tranh đẹp để tặng cô giáo. Cả nhóm cùng mỉm cười và cảm thấy rất vui. Đây là cảm xúc của sự gì?',
        optionA: 'Ghê tởm',
        optionB: 'Bình tĩnh',
        optionC: 'Vui vẻ',
        optionD: 'Buồn bã',
        correctAnswer: AnswerChoice.C,
      },
      {
        quizId: '5',
        emotionId: '7',
        questionType: QuestionType.text,
        content:
          'Con và bạn đang thảo luận về một bộ phim hoạt hình. Hai con có ý kiến khác nhau nhưng vẫn lắng nghe nhau và không tranh cãi. Hai con đang thể hiện điều gì?',
        optionA: 'Buồn bã',
        optionB: 'Vui vẻ',
        optionC: 'Ngạc nhiên',
        optionD: 'Bình tĩnh',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '5',
        emotionId: '4',
        questionType: QuestionType.text,
        content:
          'Khi con kể cho mẹ nghe về chiến thắng của đội bóng đá trong lớp, mẹ có thể thể hiện cảm xúc gì?',
        optionA: 'Ngạc nhiên',
        optionB: 'Sợ hãi',
        optionC: 'Giận dữ',
        optionD: 'Ghê tởm',
        correctAnswer: AnswerChoice.A,
      },
      {
        quizId: '5',
        emotionId: '6',
        questionType: QuestionType.text,
        content:
          'Trong giờ ăn trưa bạn thấy một món ăn mà bạn không thích. Bạn có thể thể hiện cảm xúc nào?',
        optionA: 'Vui vẻ',
        optionB: 'Ngạc nhiên',
        optionC: 'Bình tĩnh',
        optionD: 'Ghê tởm',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '5',
        emotionId: '1',
        questionType: QuestionType.text,
        content:
          'Trong lớp học, con nói to một câu chuyện cười và mọi người cùng cười theo. Con cảm thấy vui sướng và muốn kể thêm nữa. Đây là cảm giác gì?',
        optionA: 'Bình tĩnh',
        optionB: 'Giận dữ',
        optionC: 'Sợ hãi',
        optionD: 'Vui vẻ',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '5',
        emotionId: '5',
        questionType: QuestionType.text,
        content:
          'Khi bạn con đang bị lạc và đang tìm bố mẹ, xung quanh toàn người lạ. Bạn con đang thể hiện cảm xúc nào?',
        optionA: 'Vui vẻ',
        optionB: 'Sợ hãi',
        optionC: 'Giận dữ',
        optionD: 'Bình tĩnh',
        correctAnswer: AnswerChoice.B,
      },
      {
        quizId: '5',
        emotionId: '2',
        questionType: QuestionType.text,
        content:
          'Con và bạn cùng chơi xếp hình. Bạn con xếp được một tòa nhà rất cao, còn con thì chưa. Con cảm thấy không vui lắm khi nhìn thấy tòa nhà của bạn. Đây có thể là cảm xúc nào?',
        optionA: 'Buồn bã',
        optionB: 'Ngạc nhiên',
        optionC: 'Ghê tởm',
        optionD: 'Vui vẻ',
        correctAnswer: AnswerChoice.A,
      },

      // level 3 quiz 2
      {
        quizId: '6',
        emotionId: '3',
        questionType: QuestionType.text,
        content:
          'Con thấy bạn Hùng đang nhíu chặt lông mày, mím môi và nắm chặt tay. Cảm xúc nào có khả năng Hùng đang cảm thấy?',
        optionA: 'Ngạc nhiên',
        optionB: 'Buồn bã',
        optionC: 'Giận dữ',
        optionD: 'Sợ hãi',
        correctAnswer: AnswerChoice.C,
      },
      {
        quizId: '6',
        emotionId: '4',
        questionType: QuestionType.text,
        content:
          'Mẹ con vừa bước vào nhà, mắt mẹ mở to, miệng hơi há ra và mẹ đặt tay lên má. Mẹ đang cảm thấy gì?',
        optionA: 'Vui vẻ',
        optionB: 'Ngạc nhiên',
        optionC: 'Bình tĩnh',
        optionD: 'Ghê tởm',
        correctAnswer: AnswerChoice.B,
      },
      {
        quizId: '6',
        emotionId: '1',
        questionType: QuestionType.text,
        content:
          'Khi con nói: "Hôm nay con được điểm 10 môn Toán!", ba con nở một nụ cười rạng rỡ, giọng nói cao hơn và vỗ tay. Cảm xúc ba đang thể hiện là gì?',
        optionA: 'Ngạc nhiên',
        optionB: 'Buồn bã',
        optionC: 'Sợ hãi',
        optionD: 'Vui vẻ',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '6',
        emotionId: '2',
        questionType: QuestionType.text,
        content:
          'Con thấy một bạn ngồi trong góc, vai rũ xuống, nhìn xuống đất và lặng lẽ. Con nghĩ bạn ấy đang cảm thấy gì?',
        mediaUrl: 'media_question/level3/quiz2/q4.jpg',
        optionA: 'Ghê tởm',
        optionB: 'Giận dữ',
        optionC: 'Vui vẻ',
        optionD: 'Buồn bã',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '6',
        emotionId: '5',
        questionType: QuestionType.text,
        content:
          'Con thấy bạn Mai lùi về phía sau, hai mắt mở to, và đang che mặt bằng tay. Có vẻ như bạn ấy vừa nhìn thấy một con vật lạ. Mai đang cảm thấy gì?',
        optionA: 'Sợ hãi',
        optionB: 'Buồn bã',
        optionC: 'Vui vẻ',
        optionD: 'Bình tĩnh',
        correctAnswer: AnswerChoice.A,
      },
      {
        quizId: '6',
        emotionId: '6',
        questionType: QuestionType.text,
        content:
          'Chị con vừa ăn một miếng chanh và nhăn mũi lại, lè lưỡi và run nhẹ người. Cảm xúc nào chị con đang thể hiện?',
        optionA: 'Bình tĩnh',
        optionB: 'Sợ hãi',
        optionC: 'Ghê tởm',
        optionD: 'Ngạc nhiên',
        correctAnswer: AnswerChoice.C,
      },
      {
        quizId: '6',
        emotionId: '3',
        questionType: QuestionType.text,
        content:
          'Con chạy nhanh và vô tình va vào một bạn. Bạn ấy cau mày và nhanh chóng kéo tay lại. Cảm xúc đầu tiên của bạn ấy là gì?',
        optionA: 'Vui vẻ',
        optionB: 'Buồn bã',
        optionC: 'Ngạc nhiên',
        optionD: 'Giận dữ',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '6',
        emotionId: '1',
        questionType: QuestionType.text,
        content:
          'Khi con nói: "Con đã làm xong hết bài tập rồi ạ!", mẹ cười nhẹ, gật đầu và xoa đầu con. Mẹ đang cảm thấy gì?',
        mediaUrl: 'media_question/level3/quiz2/q8.jpg',
        optionA: 'Giận dữ',
        optionB: 'Bình tĩnh',
        optionC: 'Vui vẻ',
        optionD: 'Ghê tởm',
        correctAnswer: AnswerChoice.C,
      },

      // level 4 quiz 1
      {
        quizId: '7',
        emotionId: '1',
        questionType: QuestionType.text,
        content: 'Bạn bè cho bạn một món quà bạn rất thích. Bạn cảm thấy...',
        optionA: 'Buồn bã',
        optionB: 'Vui vẻ',
        optionC: 'Ngạc nhiên',
        optionD: 'Sợ hãi',
        correctAnswer: AnswerChoice.B,
      },
      {
        quizId: '7',
        emotionId: '7',
        questionType: QuestionType.text,
        content:
          'Thầy giáo đang đứng giảng bài, giọng thầy đều đặn, không to và thân hình thầy thư giãn. Thầy đang cảm thấy gì?',
        optionA: 'Giận dữ',
        optionB: 'Bình tĩnh',
        optionC: 'Ghê tởm',
        optionD: 'Buồn bã',
        correctAnswer: AnswerChoice.B,
      },
      {
        quizId: '7',
        emotionId: '2',
        questionType: QuestionType.text,
        content:
          'Bạn của con vừa bị mẹ mắng. Khi con hỏi thăm, bạn ấy mắt rưng rưng, giọng nói run run và quay mặt đi chỗ khác. Bạn ấy đang cảm thấy gì?',
        mediaUrl: 'media_question/level4/quiz1/q4.jpg',
        optionA: 'Bình tĩnh',
        optionB: 'Ngạc nhiên',
        optionC: 'Buồn bã',
        optionD: 'Giận dữ',
        correctAnswer: AnswerChoice.C,
      },
      {
        quizId: '7',
        emotionId: '3',
        questionType: QuestionType.text,
        content:
          'Con thấy bố con mặt mày nghiêm trọng, hai tay khoanh trước ngực, và nhìn con chằm chằm. Bố đang thể hiện cảm xúc gì?',
        optionA: 'Giận dữ',
        optionB: 'Bình tĩnh',
        optionC: 'Sợ hãi',
        optionD: 'Vui vẻ',
        correctAnswer: AnswerChoice.A,
      },
      {
        quizId: '7',
        emotionId: '5',
        questionType: QuestionType.text,
        content:
          'Cô giáo giải bài toán nhưng bạn không hiểu gì cả. Bạn nghĩ về cảnh cô giáo mắng mình. Bạn đang cảm thấy...',
        optionA: 'Buồn bã',
        optionB: 'Sợ hãi',
        optionC: 'Ngạc nhiên',
        optionD: 'Ghê tởm',
        correctAnswer: AnswerChoice.B,
      },
      {
        quizId: '7',
        emotionId: '1',
        questionType: QuestionType.text,
        content:
          'Bạn của con kể về chuyến đi chơi công viên nước và nói nhanh, dùng nhiều từ mạnh (như "siêu vui", "thật tuyệt vời"), và hai tay cứ vung lên. Bạn ấy đang cảm thấy thế nào?',
        optionA: 'Giận dữ',
        optionB: 'Bình tĩnh',
        optionC: 'Buồn bã',
        optionD: 'Vui vẻ',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '7',
        emotionId: '2',
        questionType: QuestionType.text,
        content:
          'Bạn con vừa khoe một chiếc áo mới rất đẹp và đắt tiền. Con không nói gì, nhưng trong bụng con ước gì mình cũng có chiếc áo đó. Cảm xúc trong bụng con là gì?',
        optionA: 'Bình tĩnh',
        optionB: 'Ghê tởm',
        optionC: 'Sợ hãi',
        optionD: 'Buồn bã',
        correctAnswer: AnswerChoice.D,
      },
      {
        quizId: '7',
        emotionId: '1',
        questionType: QuestionType.text,
        content:
          'Con tặng bạn một chiếc bút chì đẹp, và bạn ấy cười rất tươi, nói "Cảm ơn bạn". Con cảm thấy ấm áp trong lòng. Đây là cảm xúc gì?',
        optionA: 'Buồn bã',
        optionB: 'Ngạc nhiên',
        optionC: 'Vui vẻ',
        optionD: 'Ghê tởm',
        correctAnswer: AnswerChoice.C,
      },
    ],
  });

  console.log('✅ Seed finished');
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
